### ISSUE TITLE
Tester la visite du site

### ISSUE THREAD

**Issue by Jetinho** [Jetinho/compost-lyon#34]

**Comment by Jetinho** [comment]
Dans #62 

Ressources utiles pour comprendre circleci et la configuration : 

https://circleci.com/blog/docker-what-you-should-know/

https://circleci.com/docs/2.0/postgres-config/

**Comment by Jetinho** [comment]
Probleme au lancement des test assc/engine.rb:43: [BUG] Segmentation fault at
https://github.com/sass/sassc-ruby/issues/207

--> https://github.com/Jetinho/compost-lyon/pull/62/commits/0930152e66acbf3bb9a57649994585d98c5a28fd

**Comment by Jetinho** [comment]
Les test se lancent mais crash

```
     Failure/Error: @import "bootstrap/scss/bootstrap";
     
     ActionView::Template::Error:
       Error: File to import not found or unreadable: bootstrap/scss/bootstrap.
               on line 7:1 of app/assets/stylesheets/application.scss
       >> @import "bootstrap/scss/bootstrap";
     
          ^
     # ./app/assets/stylesheets/application.scss:7
     # /usr/local/bundle/ruby/2.6.0/gems/sassc-2.4.0/lib/sassc/engine.rb:50:in `render'
     # /usr/local/bundle/ruby/2.6.0/gems/sassc-rails-2.1.2/lib/sassc/rails/template.rb:40:in `block in call'
```

https://stackoverflow.com/questions/55570569/rails-4-getting-webpacker-to-work-with-circleci
